name: Build images arm64

on:
  workflow_dispatch:

jobs:
  build_images_arm64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64]
    
    steps:
    - uses: actions/checkout@v2

    - name: check path
      run: |
        pwd

    - name: Configure Git
      run: |
        git config --global user.name "daily-update"
        git config --global user.email "tg@spiritlhl.top"
      
    - name: Build and Upload Images
      run: |
        for distro in debian ubuntu kali centos almalinux rockylinux alpine openwrt oracle archlinux; do
          bash build_images.sh $distro
          
          release_id=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/oneclickvirt/lxc_amd64_images/releases/tags/$distro" \
            | jq -r '.id')
    
          existing_asset_id=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/oneclickvirt/lxc_amd64_images/releases/$release_id/assets" \
            | jq -r --arg name "$(basename "$file")" '.[] | select(.name == $name) | .id')
    
          if [ -n "$existing_asset_id" ]; then
            curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/oneclickvirt/lxc_amd64_images/releases/assets/$existing_asset_id"
          fi
    
          for file in *.zip; do
            echo "\nUploading $file to release..."
            curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: application/zip" \
              --data-binary @"$file" \
              "https://uploads.github.com/repos/oneclickvirt/lxc_amd64_images/releases/$release_id/assets?name=$(basename "$file")"
          done
        done
